apiVersion: v1
kind: Service
metadata:
  name: my-redis
  labels:
    app: my-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis-deploy
  selector:
    app: my-redis
  type: LoadBalancer